'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Header

    '''<summary>
    '''navBeranda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navBeranda As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''navKoleksi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navKoleksi As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''navLayanan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navLayanan As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''navKontak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navKontak As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
